name: Build Processing Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Processing 4.3
        run: |
          wget https://github.com/processing/processing4/releases/download/processing-1293-4.3/processing-4.3-linux-x64.tgz
          tar -xvzf processing-4.3-linux-x64.tgz

      - name: Install Libraries
        run: |
          mkdir -p ~/sketchbook/libraries
          wget -O video.zip https://github.com/processing/processing-video/releases/download/latest/video.zip
          unzip video.zip -d ~/sketchbook/libraries/
          wget -O sound.zip https://github.com/processing/processing-sound/releases/download/v2.4.0/sound.zip
          unzip sound.zip -d ~/sketchbook/libraries/

      - name: Export Application
        run: |
          # Eliminamos la carpeta out por seguridad antes de empezar
          rm -rf $GITHUB_WORKSPACE/out
          # Agregamos --force para que Processing gestione la creación
          ./processing-4.3/processing-java --sketch=$GITHUB_WORKSPACE/source --output=$GITHUB_WORKSPACE/out --force --export --variant=windows-amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OutOfBounds-Windows-App
          path: out/