name: Build Processing Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Processing 4.3
        run: |
          wget https://github.com/processing/processing4/releases/download/processing-1293-4.3/processing-4.3-linux-x64.tgz
          tar -xvzf processing-4.3-linux-x64.tgz

      - name: Install Libraries
        run: |
          # Crear la carpeta donde Processing busca por defecto en Linux
          mkdir -p ~/sketchbook/libraries
          
          # Descargar Video con el link solicitado
          wget -O video.zip https://github.com/processing/processing-video/releases/download/latest/video.zip
          unzip video.zip -d ~/sketchbook/libraries/
          
          # Descargar Sound
          wget -O sound.zip https://github.com/processing/processing-sound/releases/download/v2.4.0/sound.zip
          unzip sound.zip -d ~/sketchbook/libraries/

      - name: Compile Sketch
        run: |
          # Ejecución sin el parámetro --sketchbook
          ./processing-4.3/processing-java --sketch=$GITHUB_WORKSPACE/source --output=$GITHUB_WORKSPACE/build --build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OutOfBounds-Build
          path: build/